# Generated by Django 3.1.1 on 2021-07-18 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='دسته بندی نشده', max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sold_amount', models.IntegerField(default=0)),
                ('buyer_full_name', models.CharField(max_length=300)),
                ('buyer_address', models.CharField(max_length=1000)),
                ('price', models.FloatField(default=0)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('در حال انجام', 'در حال انجام'), ('انجام شده', 'انجام شده'), ('لفو شده', 'لغو شده')], default='در حال انجام', max_length=100)),
            ],
        ),
    ]
