# Generated by Django 3.1.1 on 2021-07-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('available_amount', models.IntegerField(default=0)),
                ('sold_amount', models.IntegerField(default=0)),
                ('image', models.ImageField(default='product.png', upload_to='uploaded_product/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category')),
            ],
        ),
    ]
