# Generated by Django 3.1.1 on 2021-07-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210718_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
